# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39f9c53a9d9cc8d54c3fd86ba2f8c45c8cf0b079c09e3907813c239075fe21c6cf7265bb7bc39bd31171d5b6f810cf136bd082676503c0afffbb723aafab4683

test:
  secret_key_base: 50248057ff2e3299e882ede5456e8056920507971222f50b323df3582efde5261410fb0ca524dfe17e0daecf48516c56c1d389c041d589fd3cdd33cbc19f9d0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
